import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Clock } from 'lucide-react';
import SocialLinks from './SocialLinks';
import { zoomBookingUrl } from './siteBooking';

export const cbnArticlePath = '/blog/cbn-data-localisation-migration';
const title = 'CBN’s payment data localisation policy: planning a reliable migration';
const officialCircular = 'https://www.cbn.gov.ng/Out/2026/CCD/CIRCULAR%20ON%20INTRODUCTION%20OF%20MARKET%20STRUCTURE%20REQUIREMENTS,%20DATA%20LOCALISATION,%20ULTIMATE%20BENEFICIAL%20OWNERSHIP%20DISCLOSURE,%20AND%20SYSTEMIC%20OVERSIGHT%20MEASURES%20IN%20THE%20NIGERIA%20PAYMENTS%20SYSTEM.pdf';
const legalAnalysis = 'https://pavestoneslegal.com/cbns-data-localisation-directive-compliance-considerations-for-payment-system-participants/';

export function BlogFeature() {
  return <section className="bl-blog-feature ng-container" aria-label="Latest article"><img src="/images/conference-work.jpg" alt="Technology professionals reviewing a plan together" width="1400" height="933" loading="lazy" /><div><p className="ng-kicker">CLOUD & DATA GOVERNANCE · 9 OCTOBER 2026</p><h2><Link to={cbnArticlePath}>{title}</Link></h2><p>What the January 2027 requirement means for Nigerian payment operators—and how to plan the move without losing control of service reliability.</p><Link className="ng-link" to={cbnArticlePath}>Read the article <ArrowRight size={18} /></Link></div></section>;
}

export function BlogIndex() {
  useEffect(() => { document.title = 'Blog | BlueLink Consults'; }, []);
  return <main><section className="ng-about-hero"><p className="eyebrow">BlueLink Consults · Blog</p><h1>Practical thinking for reliable technology.</h1><p>Perspectives on cloud infrastructure, data governance and the decisions behind dependable delivery.</p></section><BlogFeature /><section className="bl-blog-follow ng-container"><h2>Keep up with BlueLink</h2><p>Follow our team for new articles, event highlights and technology updates.</p><SocialLinks /></section></main>;
}

export function CbnArticle() {
  useEffect(() => { document.title = `${title} | BlueLink Consults`; }, []);
  return <main className="bl-editorial"><header className="bl-article-header ng-container"><Link className="ng-link" to="/blog">Back to Blog</Link><p className="ng-kicker">CLOUD & DATA GOVERNANCE</p><h1>{title}</h1><p className="bl-article-deck">The deadline is a business responsibility. The migration needs an engineering plan.</p><p className="bl-article-meta">BlueLink Consults · <time dateTime="2026-10-09">9 October 2026</time> · <Clock size={16} aria-hidden="true" /> 6 min read</p></header><article className="bl-article-body">
    <p>A payment service can look local to its customers while its database, backups and supporting systems sit in several countries. Moving that environment takes more than choosing a Nigerian hosting provider. It requires a clear view of where data travels, what the applications depend on and how the team will keep transactions working during the change.</p>
    <section id="policy"><h2>What the CBN circular requires</h2><p>The Central Bank of Nigeria’s circular <strong>PSS/DIR/PUB/CIR/001/004, dated 15 June 2026</strong>, requires financial institutions and participants facilitating payments in Nigeria to store and manage payment transaction data generated within Nigeria in Nigeria. Full compliance with that requirement takes effect on <strong>1 January 2027</strong>. <a href={officialCircular}>Read the circular, paragraph 2.</a></p><p>The circular addresses banks, microfinance banks, mobile money operators, switching and processing companies, payment service providers and other licensed payment operators. It also covers ownership disclosure and market structure; this article focuses on the data migration work.</p><p>The wording concerns payment transaction data. It should not be presented as an instruction to move every business application or every category of information. Your compliance and legal teams should confirm the scope for your institution and track subsequent CBN guidance.</p></section>
    <aside className="bl-policy-note"><strong>A local backup is not a complete migration plan.</strong><p>If the operational database stays offshore, a copy in Nigeria alone does not establish that the data is stored and managed locally. Review processing, replicas, administration and third-party flows with your compliance team. <a href={legalAnalysis}>See Pavestones’ analysis of these questions.</a></p></aside>
    <section id="inventory"><h2>1. Establish where the data actually lives</h2><p>Start with a system inventory that engineers can verify. For each payment-related data store, record its owner, physical hosting location, information types, retention period and upstream and downstream systems. Include production databases, object storage, queues, caches, backups, logs, exports and testing environments that use production data.</p><p>Then trace a transaction from the customer’s request through authorization, settlement and reconciliation. A third-party API or an error-monitoring tool can create another copy outside the main database. Record those flows instead of assuming the database region tells the whole story.</p></section>
    <section id="target"><h2>2. Choose an operating model, not just a server</h2><p>Assess potential providers against the actual workload: database support, network connectivity, capacity, incident response, backup recovery and the availability commitments your customers depend on. Ask for evidence of the hosting location and clarify subcontractors, support access, audit rights and exit arrangements.</p><p>Define who owns identity, encryption keys, patching, monitoring and recovery. Agree recovery time and recovery point objectives before procurement. A domestic address does not, by itself, tell you whether the service can survive a failed node or restore a damaged database.</p></section>
    <section id="migration"><h2>3. Rehearse the migration before changing production</h2><p>Build a representative staging environment and test the application against the target platform. Check database extensions, connection limits, certificates, secrets, service accounts, scheduled jobs and integrations. Measure performance under realistic transaction patterns.</p><p>For a continuously updated database, define how the initial copy and subsequent changes will be synchronized. Establish acceptance checks for record counts, transaction totals and reconciliation exceptions. The cutover plan should name the decision owner, the allowed maintenance window, the conditions for stopping and the rollback procedure.</p><p>Rehearse the runbook. “We have a backup” is weaker evidence than a successful restore and a timed recovery exercise.</p></section>
    <section id="evidence"><h2>4. Keep evidence of the result</h2><p>After cutover, verify both technical operation and the agreed data-location controls. Review remaining replicas, exports and vendor connections. Retire obsolete environments through an approved retention and deletion process, with records of the actions taken.</p><div className="bl-table-wrap"><table><caption>A practical migration evidence pack</caption><thead><tr><th>Area</th><th>Evidence to retain</th></tr></thead><tbody><tr><td>Data location</td><td>Inventory, data-flow map and provider location evidence</td></tr><tr><td>Security</td><td>Access reviews, encryption configuration and audit logs</td></tr><tr><td>Reliability</td><td>Performance results, restore tests and recovery timings</td></tr><tr><td>Cutover</td><td>Approved runbook, reconciliation checks and sign-off</td></tr><tr><td>Operations</td><td>Named owners, monitoring, escalation and support procedures</td></tr></tbody></table></div><p>These are BlueLink’s recommended engineering deliverables, rather than a prescribed CBN checklist. Your institution’s compliance team should determine the evidence required for its regulatory obligations.</p></section>
    <section id="bluelink"><h2>Where BlueLink can help</h2><p>BlueLink’s Technology Audit & Assessment service can help establish the current environment and its dependencies. Cloud Infrastructure and Application Modernization support the target platform and application changes. DevOps & Automation makes configuration repeatable; Pre-Deployment Validation checks readiness before cutover; Operational & Incident Support helps the team run the resulting environment.</p><p>A useful starting point is a scoped readiness assessment: what exists, what needs to change, who owns the work and how success will be demonstrated.</p><a className="ng-btn" href={zoomBookingUrl}>Schedule a 30-minute discussion <ArrowRight size={18} /></a></section>
    <section className="bl-article-sources" id="sources"><h2>Sources and further reading</h2><ol><li><a href={officialCircular}>CBN circular PSS/DIR/PUB/CIR/001/004, 15 June 2026</a> — the source document; paragraph 2 sets out the localisation requirement. <a href="https://www.scribd.com/document/1060014541/CIRCULAR-ON-INTRODUCTION-OF-MARKET-STRUCTURE-REQUIREMENTS-DATA-LOCALISATION-ULTIMATE-BENEFICIAL-OWNERSHIP-DISCLOSURE-AND-SYSTEMIC-OVERSIGHT-MEASURE">Read a reproduced copy</a> if the CBN download is unavailable.</li><li><a href={legalAnalysis}>Pavestones Legal: compliance considerations for payment system participants</a>, 3 July 2026 — interpretation of operational and contractual issues.</li><li><a href="https://www.ndpc.gov.ng/ndp-act-2023/">Nigeria Data Protection Commission: Nigeria Data Protection Act 2023</a> — the wider personal-data protection framework.</li></ol><p className="bl-editorial-note">Policy text reviewed on 9 October 2026 using a reproduced copy of the CBN circular and corroborating legal commentary; the official PDF was unavailable during review. Operational steps are BlueLink’s engineering recommendations. Confirm institution-specific obligations and later guidance with your compliance and legal advisers.</p></section>
    <section className="bl-article-follow"><h2>Follow BlueLink Consults</h2><p>More practical guidance, industry updates and event highlights from our team.</p><SocialLinks /></section>
  </article></main>;
}
