import React,{useState,useRef} from 'react';
import {Link} from 'react-router-dom';
import {BarChart3,Download,Share2,ChevronRight,Building2,Upload,RotateCcw,FileText,Calculator} from 'lucide-react';
import {MODULES,validate,analyse} from './simulatorModel';
import {CONTACTS,createReport} from './simulatorReport';
import './enterpriseSimulator.css';
export default function EnterpriseSimulator(){
 const [active,setActive]=useState('cost'),[values,setValues]=useState({}),[client,setClient]=useState({company:'',contact:'',scenario:''}),[logo,setLogo]=useState(''),[currency,setCurrency]=useState('NGN'),[result,setResult]=useState(null),[errors,setErrors]=useState({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const heading=useRef(null),fileInput=useRef(null);const module=MODULES.find(m=>m.id===active);const input=values[active]||{};
 function switchModule(id){setActive(id);setResult(null);setErrors({});setMessage('');}
 function update(k,v){setValues(old=>({...old,[active]:{...(old[active]||{}),[k]:v}}));setResult(null);setErrors(old=>({...old,[k]:undefined}));}
 function run(e){e.preventDefault();const errs=validate(module,input);setErrors(errs);if(Object.keys(errs).length){setMessage('Complete the highlighted fields before running your scenario.');return;}
 setResult({...analyse(module,input,currency),sample:!!input._example,client:{...client},logo,createdAt:new Date().toLocaleString('en-GB'),id:'BL-'+Date.now().toString(36).toUpperCase()});setMessage('');requestAnimationFrame(()=>{heading.current?.scrollIntoView({behavior:'smooth',block:'start'});heading.current?.focus({preventScroll:true});});}
 async function upload(e){const file=e.target.files?.[0];if(!file)return;if(!['image/png','image/jpeg'].includes(file.type)||file.size>2*1024*1024){setMessage('Choose a PNG or JPEG logo smaller than 2 MB.');e.target.value='';return;}
 try{const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});await new Promise((resolve,reject)=>{const image=new Image();image.onload=resolve;image.onerror=reject;image.src=data;});setLogo(data);setResult(null);setMessage('');}catch{setMessage('This logo could not be read. Choose a different PNG or JPEG.');}}
 async function exportReport(share=false){if(!result)return;setBusy(true);setMessage('');try{const report=await createReport(result,result.client,result.logo);const file=new File([report.blob],report.filename,{type:'application/pdf'});if(share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:result.title,text:'Technology assessment for '+(result.client.company||'our team')});}else{const url=URL.createObjectURL(report.blob),a=document.createElement('a');a.href=url;a.download=report.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);if(share)setMessage('Your PDF has downloaded. Attach it to your team email or messaging app.');}}catch(e){if(e.name!=='AbortError')setMessage('The report could not be generated. Please try again.');}finally{setBusy(false);}}
 return <main className="es-app">
 <div className="es-masthead"><div><p className="es-eyebrow">BLUELINK CONSULTS</p><h1>Technology assessment workspace</h1><p>Model a target state. Understand the assumptions. Plan the next decision.</p></div><span className="es-label"><Calculator size={16}/> Scenario planning</span></div>
 <div className="es-layout"><aside className="es-sidebar"><p>ASSESSMENT AREAS</p><nav aria-label="Assessment areas">{MODULES.map((m,i)=><button key={m.id} type="button" onClick={()=>switchModule(m.id)} aria-current={active===m.id?'page':undefined}><span className="es-number">0{i+1}</span><span>{m.title}</span><ChevronRight size={15}/></button>)}</nav><div className="es-sidebar-note"><FileText size={20}/><strong>A report your team can use</strong><span>Inputs, scenario results, priorities and calculation methods in one branded PDF.</span></div><Link to="/request-demo" className="es-advisor">Discuss with BlueLink</Link></aside>
 <section className="es-workspace"><div className="es-work-head"><div><p className="es-eyebrow">{result?'RESULTS DASHBOARD':'CONFIGURE YOUR ASSESSMENT'}</p><h2>{module.title}</h2><p>{module.description}</p></div><button type="button" className="es-text-button" onClick={()=>{setResult(null);setValues(old=>({...old,[active]:{}}));setErrors({});setMessage('');}}><RotateCcw size={15}/> Reset area</button></div>
 {message&&<div className="es-message" role="status">{message}</div>}
 {!result?<form onSubmit={run} noValidate><section className="es-section"><div className="es-section-title"><span>01</span><div><h3>Report identity</h3><p>Add your organisation and logo for the downloadable report.</p></div></div><div className="es-form-grid"><label>Organisation name<input maxLength={120} value={client.company} onChange={e=>setClient({...client,company:e.target.value})} placeholder="Your organisation"/></label><label>Prepared for<input maxLength={120} value={client.contact} onChange={e=>setClient({...client,contact:e.target.value})} placeholder="Team or contact name"/></label><label>Scenario name<input maxLength={120} value={client.scenario} onChange={e=>setClient({...client,scenario:e.target.value})} placeholder="For example: Infrastructure review"/></label><label>Reporting currency<select value={currency} onChange={e=>setCurrency(e.target.value)}><option value="NGN">NGN — Nigerian naira</option><option value="USD">USD — US dollar</option><option value="GBP">GBP — British pound</option><option value="EUR">EUR — Euro</option></select></label></div><div className="es-logo-row">{logo?<img src={logo} alt="Client logo preview"/>:<Building2 size={28}/>}<div><strong>Client logo</strong><span>PNG or JPEG, up to 2 MB. Optional.</span></div><label className="es-upload"><Upload size={16}/> Upload logo<input ref={fileInput} type="file" accept="image/png,image/jpeg" onChange={upload}/></label>{logo&&<button type="button" className="es-text-button" onClick={()=>{setLogo('');if(fileInput.current)fileInput.current.value='';}}>Remove</button>}</div></section>
 <section className="es-section"><div className="es-section-title"><span>02</span><div><h3>Current state and target assumptions</h3><p>Enter your own figures. Use Unknown for controls you cannot confirm.</p></div><button className="es-text-button" type="button" onClick={()=>{setValues(old=>({...old,[active]:{...module.sample,_example:true}}));setErrors({});setMessage('Illustrative example loaded. Replace these figures before using the results for your organisation.');}}>Load example</button></div><div className="es-form-grid">{module.fields.map(([key,label,type,min,max])=><label key={key} htmlFor={'es-'+key}>{label}{type==='select'?<select id={'es-'+key} value={input[key]||''} aria-invalid={!!errors[key]} aria-describedby={errors[key]?'error-'+key:undefined} onChange={e=>update(key,e.target.value)}><option value="">Choose a response</option><option value="yes">Yes</option><option value="no">No</option><option value="unknown">Unknown</option></select>:<input id={'es-'+key} type="number" inputMode="decimal" step="any" min={min} max={max} value={input[key]??''} aria-invalid={!!errors[key]} aria-describedby={errors[key]?'error-'+key:undefined} onChange={e=>update(key,e.target.value)} placeholder="Enter value"/>}{errors[key]&&<small id={'error-'+key} className="es-error">{errors[key]}</small>}</label>)}</div></section><div className="es-run-row"><p>This assessment runs in your browser. BlueLink receives no inputs or logo unless you choose to share your report.</p><button className="es-primary" type="submit"><BarChart3 size={18}/> Run assessment</button></div></form>:<div className="es-results"><div className="es-report-bar"><div>{result.logo&&<img src={result.logo} alt="Client logo"/>}<div><strong>{result.client.company||'Organisation assessment'}</strong><span>{result.client.scenario||result.title} · {result.id}</span></div></div><div className="es-report-actions"><button type="button" onClick={()=>exportReport()} disabled={busy}><Download size={16}/>{busy?'Preparing PDF…':'Download PDF'}</button><button type="button" onClick={()=>exportReport(true)} disabled={busy}><Share2 size={16}/> Share with team</button></div></div>
 <div className="es-result-heading"><h3 ref={heading} tabIndex={-1}>Scenario overview</h3><span>{result.sample?'Illustrative example · ':'Preliminary · '}{result.createdAt}</span></div><div className="es-metrics">{result.metrics.map(m=><article key={m.label}><p>{m.label}</p><strong>{m.value}</strong><span>{m.detail}</span></article>)}</div>
 <div className="es-result-columns"><section className="es-section"><h3>Current and desired state</h3><div className="es-table-wrap"><table><thead><tr><th scope="col">Measure</th><th scope="col">Current</th><th scope="col">Desired scenario</th></tr></thead><tbody>{result.comparison.map(r=><tr key={r.label}><th scope="row">{r.label}</th><td>{r.current}</td><td>{r.target}</td></tr>)}</tbody></table></div></section><section className="es-section"><h3>Priorities and evidence</h3>{result.findings.map((f,i)=><article className="es-finding" key={i}><span className={'es-priority es-'+f.priority.toLowerCase()}>{f.priority}</span><div><h4>{f.title}</h4><p>{f.detail}</p></div></article>)}</section></div>
 <section className="es-section"><h3>Recommended next steps</h3><ol className="es-next">{result.actions.map(a=><li key={a}>{a}</li>)}</ol></section><details className="es-assumptions"><summary>Inputs, assumptions and calculation basis</summary><p>These results use your entries and transparent scenario rules. They do not represent a system inspection, vendor quotation or compliance certification.</p><ul>{result.assumptions.map(a=><li key={a}>{a}</li>)}</ul><dl>{result.inputs.map(i=><div key={i.label}><dt>{i.label}</dt><dd>{i.value}</dd></div>)}</dl><p>The PDF includes the calculation method and all inputs.</p></details>
 <div className="es-result-bottom"><button className="es-secondary" onClick={()=>setResult(null)}>Edit scenario</button><Link className="es-primary" to="/request-demo">Request a technical assessment</Link></div><div className="es-contact-strip"><strong>BlueLink Consults</strong><a href="tel:+2348068649496">{CONTACTS.phones[0]}</a><a href="tel:+14014402434">{CONTACTS.phones[1]}</a><a href={'mailto:'+CONTACTS.email}>{CONTACTS.email}</a><a href={CONTACTS.website}>bluelinkconsults.ng</a>{CONTACTS.socials.map(([name,url])=><a key={name} href={url} target="_blank" rel="noopener noreferrer">{name}</a>)}</div></div>}
 </section></div></main>;
}
