const SUPABASE_URL = "https://kqjyubxrbjyvakpvcymc.supabase.co";
const SUPABASE_KEY = "sb_publishable_yNpvKpFRVhqTs02wclmX6A_FJwhg_5c";
const STORE = "bluelink_simulator_state_v3";
const fresh = () => ({ sessionId: crypto.randomUUID(), started: false, stack: [], services: [], modules: [], users: 2000 });
let state; try { state = JSON.parse(sessionStorage.getItem(STORE)) || fresh(); } catch { state = fresh(); }
const save = () => sessionStorage.setItem(STORE, JSON.stringify(state));

async function record(eventType, extra={}) {
  if (location.pathname !== "/simulator") return;
  const payload={session_id:state.sessionId,event_type:eventType,status:eventType==="completed"?"completed":eventType==="started"?"started":"in_progress",last_step:Math.min(4,Number(extra.last_step??0)),technology_stack:state.stack,legacy_services:state.services,modernization_modules:state.modules,user_count:state.users,page_path:location.pathname,referrer:document.referrer||null,user_agent:navigator.userAgent,completed_at:eventType==="completed"?new Date().toISOString():null,...extra};
  try { const r=await fetch(`${SUPABASE_URL}/rest/v1/simulator_sessions`,{method:"POST",headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify(payload),keepalive:true}); if(!r.ok) console.error("Simulator analytics failed",r.status,await r.text()); } catch(e){ console.error("Simulator analytics failed",e); }
}

const TECH=["JavaScript","TypeScript","Node.js","Python","Java","C# / .NET","C / C++","PHP","Ruby","Go","Rust","Kotlin","Swift","Scala","Perl","COBOL","Visual Basic 6","ColdFusion","AS/400 / RPG","Dart","Elixir","Haskell","MATLAB","R","Groovy","Objective-C"];
const LEARN={
 "Docker":["Packages an application and its dependencies into portable containers.","https://docs.docker.com/get-started/"],
 "Kubernetes":["Runs, scales and manages containerized applications across clusters of machines.","https://kubernetes.io/docs/concepts/overview/"],
 "CI/CD pipeline":["Automates building, testing and safely releasing software changes.","https://docs.github.com/actions"],
 "Cloud migration":["Moves applications, data or infrastructure to managed cloud platforms.","https://learn.microsoft.com/azure/cloud-adoption-framework/"],
 "REST APIs":["A common web API approach for connecting applications and services over HTTP.","https://developer.mozilla.org/en-US/docs/Glossary/REST"],
 "SSO & OAuth 2.0":["Centralizes sign-in and delegated access so users and applications authenticate more safely.","https://oauth.net/2/"],
 "Observability stack":["Combines metrics, logs and traces to understand system health and diagnose problems.","https://opentelemetry.io/docs/what-is-opentelemetry/"],
 "Microservices":["Separates selected business capabilities into independently deployable services.","https://learn.microsoft.com/azure/architecture/guide/architecture-styles/microservices"],
 "Cloud database":["Uses managed database services to reduce infrastructure operations and improve resilience options.","https://aws.amazon.com/products/databases/learn/"],
 "CDN & edge caching":["Caches content closer to users to reduce latency and origin load.","https://developer.mozilla.org/en-US/docs/Glossary/CDN"],
 "Infrastructure as Code":["Defines infrastructure in version-controlled code for repeatable, reviewable environments.","https://developer.hashicorp.com/terraform/intro"],
 "Security hardening":["Reduces attack surface through stronger identity, network, configuration and application controls.","https://www.cisa.gov/resources-tools/resources/cybersecurity-performance-goals"],
 "API gateway":["Provides a controlled entry point for APIs with routing, authentication, throttling and policy enforcement.","https://learn.microsoft.com/azure/api-management/api-management-key-concepts"],
 "Data pipeline modern.":["Modernizes how data is collected, transformed, moved and delivered for operational or analytical use.","https://learn.microsoft.com/azure/architecture/data-guide/"],
 "Message queues":["Decouples services by allowing work and events to be processed asynchronously and reliably.","https://aws.amazon.com/message-queue/"],
 "AI / ML integration":["Adds model-driven prediction, extraction, generation or automation where it has measurable business value.","https://learn.microsoft.com/azure/architecture/ai-ml/"],
};

function selectedLabels(){return [...document.querySelectorAll(".sim-opt.on .sim-ol")].map(x=>x.textContent.trim());}
function syncContinue(){
  if(!document.querySelector(".sim-ey")?.textContent.includes("Step 1")) return;
  const btn=document.querySelector("#sn1");
  if(!btn) return;
  const hasStack=state.stack.length>0 || selectedLabels().length>0;
  btn.disabled=!hasStack;
  if(hasStack){btn.removeAttribute("disabled");btn.setAttribute("aria-disabled","false");}
}
function captureStep(){const step=document.querySelector(".sim-ey")?.textContent||"",labels=selectedLabels();if(step.includes("Step 1")){const custom=[...document.querySelectorAll(".bl-stack-chip")].map(x=>x.dataset.value);state.stack=[...new Set([...labels,...custom])];}if(step.includes("Step 2"))state.services=labels;if(step.includes("Step 4"))state.modules=labels;const slider=document.querySelector("#susl");if(slider)state.users=Number(slider.value||2000);save();syncContinue();}

function addStackSearch(){if(!document.querySelector(".sim-ey")?.textContent.includes("Step 1")||document.querySelector("#bl-stack-search"))return;const grid=document.querySelector(".sim-g2");if(!grid)return;const box=document.createElement("div");box.id="bl-stack-search";box.style.cssText="grid-column:1/-1;margin:2px 0 16px;position:relative";box.innerHTML=`<div style="font-size:14px;font-weight:800;color:#0d1b2e;margin-bottom:7px">Type what your application uses</div><div style="font-size:12px;color:#5a7090;margin-bottom:9px">Not sure whether it is in our list? Start typing — for example <b>NO</b> for Node.js, <b>PY</b> for Python, or enter another technology.</div><input id="bl-stack-input" autocomplete="off" placeholder="Search or type a programming language / technology…" style="width:100%;box-sizing:border-box;padding:13px 14px;border:1.5px solid #a9cdf0;border-radius:10px;font-size:14px;outline:none;background:white"><div id="bl-stack-suggest" style="display:none;position:absolute;z-index:20;left:0;right:0;top:100%;background:white;border:1px solid #d9e4ef;border-radius:10px;box-shadow:0 12px 30px rgba(13,27,46,.14);overflow:hidden;margin-top:5px"></div><div id="bl-stack-chips" style="display:flex;gap:7px;flex-wrap:wrap;margin-top:9px"></div>`;grid.parentNode.insertBefore(box,grid);
 const input=box.querySelector("#bl-stack-input"),suggest=box.querySelector("#bl-stack-suggest"),chips=box.querySelector("#bl-stack-chips");
 const add=v=>{v=v.trim();if(!v||state.stack.some(x=>x.toLowerCase()===v.toLowerCase()))return;state.stack.push(v);save();renderChips();syncContinue();input.value="";suggest.style.display="none";record("stack_updated",{last_step:1,technology_stack:state.stack});};
 const renderChips=()=>{chips.innerHTML=state.stack.filter(x=>!selectedLabels().includes(x)).map(v=>`<span class="bl-stack-chip" data-value="${v.replace(/"/g,"&quot;")}" style="display:inline-flex;align-items:center;gap:6px;background:#eef6fd;color:#174a73;border:1px solid #c8e0f4;padding:6px 9px;border-radius:20px;font-size:12px;font-weight:700">${v}<button type="button" aria-label="Remove ${v}" style="border:0;background:none;cursor:pointer;color:#174a73;font-size:15px;line-height:1">×</button></span>`).join("");chips.querySelectorAll("button").forEach(b=>b.onclick=()=>{const v=b.parentElement.dataset.value;state.stack=state.stack.filter(x=>x!==v);save();renderChips();syncContinue();});syncContinue();};
 input.oninput=()=>{const q=input.value.trim().toLowerCase();if(!q){suggest.style.display="none";return;}const hits=TECH.filter(x=>x.toLowerCase().includes(q)).slice(0,6);suggest.innerHTML=hits.map(x=>`<button type="button" data-v="${x}" style="display:block;width:100%;text-align:left;border:0;border-bottom:1px solid #edf2f7;background:white;padding:11px 13px;cursor:pointer;font-size:13px"><b>${x}</b></button>`).join("")+(hits.some(x=>x.toLowerCase()===q)?"":`<button type="button" data-v="${input.value.trim().replace(/"/g,"&quot;")}" style="display:block;width:100%;text-align:left;border:0;background:#f7fafc;padding:11px 13px;cursor:pointer;font-size:13px;color:#378add">+ Use “${input.value.trim()}”</button>`);suggest.style.display="block";suggest.querySelectorAll("button").forEach(b=>b.onclick=()=>add(b.dataset.v));};input.onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();const first=suggest.querySelector("button");add(first?.dataset.v||input.value);}};renderChips();
}

function addLearning(){if(!document.querySelector(".sim-ey")?.textContent.includes("Step 4"))return;document.querySelectorAll(".sim-opt").forEach(opt=>{if(opt.querySelector(".bl-info"))return;const label=opt.querySelector(".sim-ol")?.textContent.trim(),data=LEARN[label];if(!data)return;const b=document.createElement("button");b.type="button";b.className="bl-info";b.setAttribute("aria-label",`Learn about ${label}`);b.innerHTML="i";b.style.cssText="margin-left:auto;flex:0 0 22px;width:22px;height:22px;border-radius:50%;border:1px solid #9cc6e9;background:#f5faff;color:#286da8;font-weight:900;font-family:serif;cursor:help;position:relative";const tip=document.createElement("div");tip.style.cssText="display:none;position:absolute;z-index:30;width:270px;right:-8px;bottom:30px;background:#0d1b2e;color:white;border-radius:11px;padding:13px;text-align:left;box-shadow:0 14px 32px rgba(0,0,0,.22);font-family:Arial,sans-serif;font-weight:400;font-size:12px;line-height:1.5";tip.innerHTML=`<strong style="font-size:13px">${label}</strong><div style="color:#d8e3ee;margin:5px 0 8px">${data[0]}</div><a href="${data[1]}" target="_blank" rel="noopener noreferrer" style="color:#7fc2ff;font-weight:800;text-decoration:none">Learn from the official documentation ↗</a>`;b.appendChild(tip);b.onmouseenter=()=>tip.style.display="block";b.onmouseleave=()=>tip.style.display="none";b.onclick=e=>{e.stopPropagation();tip.style.display=tip.style.display==="block"?"none":"block";};opt.appendChild(b);});}

function enhance(){addStackSearch();addLearning();syncContinue();}
function watch(){if(location.pathname!=="/simulator")return;if(!state.started){state.started=true;save();record("started",{last_step:0});}document.addEventListener("click",e=>{if(!e.target.closest("[class*='sim-'],#bl-stack-search"))return;setTimeout(()=>{captureStep();enhance();const txt=e.target.textContent||"";if(/Continue/.test(txt))record("progress",{last_step:Number((document.querySelector(".sim-ey")?.textContent.match(/Step (\d)/)||[0,0])[1])});if(/Run simulation/.test(txt))record("simulation_run",{last_step:4});if(/Start over/.test(txt)){state=fresh();save();record("restarted",{last_step:0});}},80);},true);const observer=new MutationObserver(()=>{captureStep();enhance();});observer.observe(document.getElementById("root")||document.body,{childList:true,subtree:true});setTimeout(enhance,300);}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",watch);else setTimeout(watch,0);
