export const CONTACTS={email:'info@bluelinkconsults.com',website:'https://www.bluelinkconsults.ng',phones:['+234 806 864 9496','+1 (401) 440-2434'],socials:[['LinkedIn','https://www.linkedin.com/company/bluelink-consults'],['Facebook','https://www.facebook.com/share/19XEu6zf1n/?mibextid=wwXIfr'],['Instagram','https://www.instagram.com/bluelinkconsults']]};
export async function createReport(result,client,logo){
 const {jsPDF}=await import('jspdf');const doc=new jsPDF();let y=0;const date=result.createdAt;const width=178;
 function header(){doc.setFillColor(17,42,70);doc.rect(0,0,210,48,'F');doc.setTextColor(255);doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text('BlueLink Consults',16,12);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text(CONTACTS.phones.join('   /   '),16,20);doc.text(CONTACTS.email+'   |   www.bluelinkconsults.ng',16,26);let x=16;for(const [name,url] of CONTACTS.socials){doc.textWithLink(name,x,34,{url});x+=28;}doc.setTextColor(200,217,236);doc.text('TECHNOLOGY SCENARIO REPORT',16,42);if(logo){doc.setFillColor(255,255,255);doc.roundedRect(157,5,39,22,1,1,'F');const im=doc.getImageProperties(logo);const scale=Math.min(35/im.width,18/im.height);doc.addImage(logo,im.fileType,159,7,im.width*scale,im.height*scale);}doc.setTextColor(24,42,64);y=61;}
 function space(h){if(y+h>276){doc.addPage();header();}}
 function line(t,size=10,bold=false){doc.setFontSize(size);doc.setFont('helvetica',bold?'bold':'normal');const rows=doc.splitTextToSize(String(t),width);space(rows.length*size*.45+4);doc.setFontSize(size);doc.setFont('helvetica',bold?'bold':'normal');doc.text(rows,16,y);y+=rows.length*size*.45+4;}
 function section(t){space(20);y+=5;line(t,12,true);}
 header();
 line(result.title,20,true);line(client.company||'Organisation not specified',12,true);line('Prepared for: '+(client.contact||'Not specified'));line('Scenario: '+(client.scenario||result.title));line('Generated: '+date+'   |   Reference: '+result.id);if(result.sample)line('ILLUSTRATIVE EXAMPLE: This report includes example figures. Replace them with your own data before making business decisions.',10,true);line('Preliminary scenario based on user inputs. Projections do not establish verified savings, performance or compliance.');
 section('Dashboard summary');for(const m of result.metrics){line(m.label+': '+m.value,11,true);line(m.detail);}
 section('Current and desired state');for(const r of result.comparison)line(r.label+'\nCurrent: '+r.current+'   /   Desired scenario: '+r.target);
 section('Findings and priorities');for(const f of result.findings){line(f.priority+' - '+f.title,11,true);line(f.detail);}
 section('Recommended next steps');result.actions.forEach((t,i)=>line((i+1)+'. '+t));
 section('Inputs and assumptions');result.inputs.forEach(t=>line(t.label+': '+t.value));line('Currency: '+result.currency);result.assumptions.forEach(t=>line(t));
 section('Calculation method');const methods={cost:'Gross reduction = spend x eligible share x target reduction. Net monthly saving = gross reduction - added operating cost. First-year benefit = net saving x 12 - implementation cost. Payback = implementation / positive net monthly saving.',modernisation:'Transaction time change = current - desired seconds. Aggregate processing change = seconds difference x monthly transactions / 3600. Relative change = seconds difference / current seconds x 100.',migration:'Bulk transfer hours = decimal GB x 8000 / (Mbps x efficiency share) / 3600. Recovery gap = maximum of zero and tested recovery hours - required recovery hours.',data:'Projected storage = current GB + monthly growth x months. Archive = current GB x eligible share. Active target = projected - archived. Target cost = active target x active rate + archive x archive rate.',audit:'Counts reflect Yes, No and Unknown responses. No answers identify reported gaps. Unknown answers identify evidence requests. No compliance rating is inferred.'};line(methods[result.module]);
 space(45);section('Discuss this assessment');line(CONTACTS.phones.join(' / '));line(CONTACTS.email);doc.textWithLink('www.bluelinkconsults.ng',16,y,{url:CONTACTS.website});
 for(let i=1;i<=doc.getNumberOfPages();i++){doc.setPage(i);doc.setFontSize(8);doc.setTextColor(90);doc.text('BlueLink Consults   |   '+result.id+'   |   '+i+' / '+doc.getNumberOfPages(),16,288);}
 return {blob:doc.output('blob'),filename:'BlueLink-'+(client.company||'Assessment').replace(/[^a-z0-9]+/gi,'-')+'-'+result.module+'.pdf'};
}
