export const CONTACTS={email:'info@bluelinkconsults.com',website:'https://www.bluelinkconsults.ng',phones:['+234 806 864 9496','+1 (401) 440-2434'],socials:[['LinkedIn','https://www.linkedin.com/company/bluelink-consults'],['Facebook','https://www.facebook.com/share/19XEu6zf1n/?mibextid=wwXIfr'],['Instagram','https://www.instagram.com/bluelinkconsults']]};
export async function createReport(result,client,logo){
 const {jsPDF}=await import('jspdf');const doc=new jsPDF();const fonts=await import('./reportFonts.js');doc.addFileToVFS('Report-Regular.ttf',fonts.regular);doc.addFileToVFS('Report-Bold.ttf',fonts.bold);doc.addFont('Report-Regular.ttf','Report','normal');doc.addFont('Report-Bold.ttf','Report','bold');doc.setFont('Report','normal');let y=0;const date=result.createdAt;const width=178;
 function header(){doc.setFillColor(17,42,70);doc.rect(0,0,210,48,'F');doc.setTextColor(255);doc.setFont('Report','bold');doc.setFontSize(16);doc.text('BlueLink Consults',16,12);doc.setFont('Report','normal');doc.setFontSize(8);doc.text(CONTACTS.phones.join('   /   '),16,20);doc.text(CONTACTS.email+'   |   www.bluelinkconsults.ng',16,26);let x=16;for(const [name,url] of CONTACTS.socials){doc.textWithLink(name,x,34,{url});x+=28;}doc.setTextColor(200,217,236);doc.text('TECHNOLOGY SCENARIO REPORT',16,42);if(logo){doc.setFillColor(255,255,255);doc.roundedRect(157,5,39,22,1,1,'F');const im=doc.getImageProperties(logo);const scale=Math.min(35/im.width,18/im.height);doc.addImage(logo,im.fileType,159,7,im.width*scale,im.height*scale);}doc.setTextColor(24,42,64);y=61;}
 function space(h){if(y+h>276){doc.addPage();header();}}
 function line(t,size=10,bold=false){doc.setFontSize(size);doc.setFont('Report',bold?'bold':'normal');const rows=doc.splitTextToSize(String(t),width);space(rows.length*size*.45+4);doc.setFontSize(size);doc.setFont('Report',bold?'bold':'normal');doc.text(rows,16,y);y+=rows.length*size*.45+4;}
 function section(t){space(20);y+=5;line(t,12,true);}
 header();
 line(result.title,20,true);line(client.company||'Organisation not specified',12,true);line('Prepared for: '+(client.contact||'Not specified'));line('Scenario: '+(client.scenario||result.title));line('Generated: '+date+'   |   Reference: '+result.id);if(result.sample)line('ILLUSTRATIVE EXAMPLE: This report includes example figures. Replace them with your own data before making business decisions.',10,true);line('Method: '+(result.version||'Declared-input scenario'));line('Scope: '+(client.scope||'Only the records supplied in this assessment. No wider organisational scope was stated.'));line('Calculated from declared inputs. Evidence references have been recorded but their content has not been independently verified.');
 section('Dashboard summary');for(const m of result.metrics){line(m.label+': '+m.value,11,true);line(m.detail);}
 section('Current and desired state');for(const r of result.comparison)line(r.label+'\nCurrent: '+r.current+'   /   Desired scenario: '+r.target);
 section('Findings and priorities');for(const f of result.findings){line(f.priority+' - '+(f.resource?f.resource+' / ':'')+f.title,11,true);line('Supporting input: '+(f.evidence||f.detail));if(f.impact)line('Business impact: '+f.impact);if(f.action)line('Recommended action: '+f.action);if(f.acceptance)line('Acceptance criterion: '+f.acceptance);if(f.owner)line('Owner: '+f.owner);if(f.rule)line('Finding '+f.id+' / Rule '+f.rule+' / Input basis: '+f.basis);}
 if(result.summary){section('Assessment interpretation');line(result.summary);} if(result.evidence?.length){section('Detailed control review');for(const item of result.evidence){line(item.label+' — '+item.status,11,true);line(item.meaning);line(item.next);}} if(result.roadmap){section('Implementation action plan');for(const item of result.roadmap){line(item.phase,11,true);line('Suggested owner: '+item.owner);item.tasks.forEach(t=>line('• '+t));line('Expected output: '+item.deliverable);}} section('Recommended next steps');result.actions.forEach((t,i)=>line((i+1)+'. '+t));
 section('Inputs and assumptions');result.inputs.forEach(t=>line(t.label+': '+t.value));line('Currency: '+result.currency);result.assumptions.forEach(t=>line(t));
 if(result.options?.length){section('Scenario options and trade-offs');for(const option of result.options){line(option.name,11,true);line(option.outcome);line(option.tradeoff);}} if(result.timeline?.length){section('Monthly projection');line(result.module==='cost'?'Cumulative cash outflow, including change cost at month zero.':'Active storage in GB. New data stays active.');for(const row of result.timeline)line('Month '+row.period+': baseline '+Math.round(row.baseline).toLocaleString('en')+' / selected scenario '+Math.round(row.scenario).toLocaleString('en'));} section('Calculation method');const methods={cost:'Gross reduction = spend x eligible share x target reduction. Net monthly saving = gross reduction - added operating cost. First-year benefit = net saving x 12 - implementation cost. Payback = implementation / positive net monthly saving.',modernisation:'Transaction time change = current - desired seconds. Aggregate processing change = seconds difference x monthly transactions / 3600. Relative change = seconds difference / current seconds x 100.',migration:'Bulk transfer hours = decimal GB x 8000 / (Mbps x efficiency share) / 3600. Recovery gap = maximum of zero and tested recovery hours - required recovery hours.',devops:'Hands-on monthly effort = releases × hands-on hours per release. Net recurring cost change = current labour value minus proposed labour value and new tooling. Horizon net benefit includes the implementation period and one-time change cost.',audit:'Counts reflect Yes, No and Unknown responses. No answers identify reported gaps. Unknown answers identify evidence requests. No compliance rating is inferred.'};if(result.methods?.length)result.methods.forEach(t=>line(t));else line(methods[result.module]);
 space(45);section('Discuss this assessment');line(CONTACTS.phones.join(' / '));line(CONTACTS.email);doc.textWithLink('www.bluelinkconsults.ng',16,y,{url:CONTACTS.website});
 for(let i=1;i<=doc.getNumberOfPages();i++){doc.setPage(i);doc.setFontSize(8);doc.setTextColor(90);doc.text('BlueLink Consults   |   '+result.id+'   |   '+i+' / '+doc.getNumberOfPages(),16,288);}
 return {blob:doc.output('blob'),filename:'BlueLink-'+(client.company||'Assessment').replace(/[^a-z0-9]+/gi,'-')+'-'+result.module+'.pdf'};
}
