export const MODULES = [
 {id:'cost',title:'Cost optimisation',short:'Cost',description:'Compare current spending with a resource reduction scenario.',fields:[['spend','Current monthly spend','number',0],['reducible','What share of your monthly spending could be changed? (%)','number',0,100],['reduction','How much do you want to reduce that changeable spending? (%)','number',0,100],['added','Additional monthly operating cost','number',0],['implementation','One-time implementation cost','number',0]],sample:{spend:1000000,reducible:60,reduction:20,added:20000,implementation:300000}},
 {id:'modernisation',title:'Application modernisation',short:'Applications',description:'Compare workflow performance and identify delivery prerequisites.',fields:[['users','Active users','number',1],['transactions','How many times is this task performed each month?','number',1],['current','How long does the task take now? (seconds)','number',0.01],['target','How quickly should the task finish? (seconds)','number',0.01],['dependencies','Have you listed the systems this application relies on?','select',['yes','no','unknown']],['tests','Do you have tests to check existing features after a change?','select',['yes','no','unknown']]],sample:{users:100,transactions:20000,current:12,target:5,dependencies:'yes',tests:'no'}},
 {id:'migration',title:'Cloud migration',short:'Migration',description:'Estimate transfer duration and compare recovery requirements.',fields:[['servers','How many servers or applications will you move?','number',1],['data','Data to transfer (GB)','number',0.01],['bandwidth','What connection speed is available for the transfer? (Mbps)','number',0.01],['efficiency','How much of that connection can the transfer use? (%)','number',1,100],['rto','How long can you wait to restore service after an outage? (hours)','number',0.01],['recovery','How long did your last recovery test take? (hours)','number',0.01],['dependencies','Have you listed the systems that must move together?','select',['yes','no','unknown']],['destination','Have you confirmed that the new hosting environment meets your needs?','select',['yes','no','unknown']]],sample:{servers:12,data:2000,bandwidth:200,efficiency:60,rto:4,recovery:8,dependencies:'no',destination:'unknown'}},
 {id:'data',title:'Data optimisation',short:'Data',description:'Model storage growth and a retention or archive scenario.',fields:[['volume','Current stored data (GB)','number',0.01],['growth','How much extra data do you keep each month? (GB)','number',0],['archive','What share of existing data could move to cheaper archive storage? (%)','number',0,100],['months','How many months ahead should we plan?','number',1,120],['rate','What do you pay for each GB of active storage each month?','number',0],['archiveRate','What would each GB of archive storage cost per month?','number',0],['backup','Have you tested recovering data from a backup?','select',['yes','no','unknown']]],sample:{volume:5000,growth:200,archive:30,months:12,rate:100,archiveRate:20,backup:'yes'}},
 {id:'audit',title:'IT & technical audit',short:'Audit',description:'Review reported controls and prioritise evidence collection.',fields:[['inventory','Do you have an up-to-date list of your IT systems?','select',['yes','no','unknown']],['access','Have you checked who can access your systems?','select',['yes','no','unknown']],['backup','Have you tested recovering data from a backup?','select',['yes','no','unknown']],['monitoring','Will your team be alerted when an important system fails?','select',['yes','no','unknown']],['patching','Is someone responsible for installing software updates?','select',['yes','no','unknown']],['response','Has your team practised responding to an outage or security incident?','select',['yes','no','unknown']],['release','Do you approve system changes and have a plan to undo them?','select',['yes','no','unknown']]],sample:{inventory:'yes',access:'no',backup:'unknown',monitoring:'yes',patching:'yes',response:'no',release:'unknown'}}
];
export const money=(n,currency='NGN')=>new Intl.NumberFormat('en',{style:'currency',currency,maximumFractionDigits:0}).format(n);
const fmt=n=>new Intl.NumberFormat('en',{maximumFractionDigits:1}).format(n);
export function validate(module,v){const errors={};for(const [key,label,type,min,max] of module.fields){if(type==='select'){if(!min.includes(v[key])) errors[key]='Select a response, including Unknown if needed.';}else if(v[key]===''||v[key]===undefined||!Number.isFinite(Number(v[key]))||Number(v[key])<min||(Number(v[key])>(max??1e12))||(['users','transactions','servers','months'].includes(key)&&!Number.isInteger(Number(v[key]))))errors[key]=`Enter a number from ${min}${max!==undefined?` to ${max}`:' or above'}.`;}return errors;}
export function analyse(module,v,currency='NGN'){
 const n=k=>Number(v[k]);const metrics=[],comparison=[],findings=[],assumptions=[],actions=[];
 const add=(label,value,detail)=>metrics.push({label,value,detail});const row=(label,current,target)=>comparison.push({label,current,target});
 if(module.id==='cost') {const gross=n('spend')*n('reducible')/100*n('reduction')/100,net=gross-n('added'),proposed=n('spend')-net;
 add('Net monthly change',money(net,currency),net>=0?'Projected monthly saving':'Projected additional monthly cost');add('Proposed monthly spend',money(proposed,currency),'After the entered additional operating cost');add('First-year net benefit',money(net*12-n('implementation'),currency),'12 months of net savings less implementation');add('Simple payback',net>0?fmt(n('implementation')/net)+' months':'No positive payback','Implementation cost / positive monthly saving');row('Monthly spend',money(n('spend'),currency),money(proposed,currency));row('Annual recurring spend',money(n('spend')*12,currency),money(proposed*12,currency));
 findings.push({priority:net>0?'Opportunity':'Review',title:net>0?'The entered scenario reduces recurring spend':'The entered scenario does not produce net savings',detail:'Gross monthly reduction is '+money(gross,currency)+'. Additional operating cost is '+money(n('added'),currency)+'.'});assumptions.push('Only the entered eligible portion of spending receives the target reduction.','Constant spending and savings for 12 months. Taxes, exchange-rate movements and financing costs excluded.','Reduction percentages are user targets, not savings identified from invoices.');actions.push('Validate invoices, utilisation and contract commitments.','Confirm engineering effort and implementation costs before approving changes.');
 } else if(module.id==='modernisation'){const change=n('current')-n('target'),hours=change*n('transactions')/3600;add('Target time change',fmt(change)+' sec',change>=0?'Reduction per workflow transaction':'Increase per workflow transaction');add('Aggregate processing change',fmt(hours)+' hours / month','Transaction-time difference multiplied by volume');add('Desired performance change',fmt(change/n('current')*100)+'%','Relative to entered current time');add('Active users',fmt(n('users')),'Reported workload context');row('Transaction time',fmt(n('current'))+' sec',fmt(n('target'))+' sec');
 assumptions.push('Transaction volume stays constant.','Aggregate processing time is not employee time saved or financial benefit.','The desired performance is a target that needs benchmarking.');actions.push('Benchmark the selected workflow and map dependencies.','Agree an architecture approach and test a representative change.');
 } else if(module.id==='migration'){const hours=n('data')*8000/(n('bandwidth')*n('efficiency')/100)/3600;add('Estimated bulk transfer',fmt(hours)+' hours','Decimal GB, entered bandwidth and efficiency');add('Workloads in scope',fmt(n('servers')),'Reported servers or workloads');add('Recovery gap',fmt(Math.max(0,n('recovery')-n('rto')))+' hours','Tested recovery time above the desired maximum');add('Recovery requirement',fmt(n('rto'))+' hours','Client target, not a demonstrated result');row('Recovery time',fmt(n('recovery'))+' hours',fmt(n('rto'))+' hours');
 if(n('recovery')>n('rto'))findings.push({priority:'High',title:'Reported recovery exceeds the requirement',detail:'Recovery design and rehearsal need to close the entered gap.'});assumptions.push('Bulk transfer estimate excludes setup, validation, retries and live data changes.','Transfer time does not equal service downtime or the full migration timeline.','Destination capacity, pricing, residency and contractual terms require separate validation.');actions.push('Inventory workloads and map application dependencies.','Run a representative transfer and rehearse reconciliation, cutover and rollback.');
 } else if(module.id==='data'){const projected=n('volume')+n('growth')*n('months'),archived=n('volume')*n('archive')/100,active=projected-archived,baseline=projected*n('rate'),target=active*n('rate')+archived*n('archiveRate');add('Projected data volume',fmt(projected)+' GB','At the end of the planning horizon');add('Target active storage',fmt(active)+' GB','Archive only the eligible portion of current data');add('Archive volume',fmt(archived)+' GB','Data remains stored in the archive scenario');add('Monthly storage difference',money(baseline-target,currency),'End-of-horizon estimate, not cumulative savings');row('Active storage',fmt(projected)+' GB',fmt(active)+' GB');row('Monthly storage cost',money(baseline,currency),money(target,currency));assumptions.push('Linear net growth. New data remains in active storage.','Archive eligibility is a user assumption subject to retention and access requirements.','Costs exclude transfer, retrieval, requests, backups and implementation.');actions.push('Confirm retention requirements and identify suitable datasets.','Measure query performance and test restoration before changing storage tiers.');
 } else {const responses=module.fields.map(([k,l])=>({label:l,value:v[k]})),yes=responses.filter(x=>x.value==='yes').length,no=responses.filter(x=>x.value==='no').length,unknown=responses.length-yes-no;add('Reported controls in place',`${yes} / ${responses.length}`,'Self-reported coverage, not a compliance score');add('Reported gaps',String(no),'Responses marked No');add('Evidence to confirm',String(unknown),'Responses marked Unknown');add('Assessment basis','Self-reported','No system inspection has taken place');responses.forEach(x=>row(x.label,x.value==='yes'?'Reported in place':x.value==='no'?'Reported missing':'Unknown','Evidence confirmed'));assumptions.push('Each response reflects the user’s knowledge at the time of assessment.','Reported controls need documentary or system evidence. This is not certification or a completed technical audit.');actions.push('Collect evidence for reported controls and unknown responses.','Agree a technical assessment scope with owners for critical systems.');}
 for(const [key,label,type] of module.fields)if(type==='select'&&v[key]!=='yes')findings.push({priority:v[key]==='no'?'High':'Verify',title:label,detail:v[key]==='no'?'Reported missing. Agree an owner and remediation plan.':'Unknown. Collect evidence before drawing a technical conclusion.'});
 if(!findings.length)findings.push({priority:'Verify',title:'Validate the scenario with system evidence',detail:'Confirm entered parameters and test the target state before implementation.'});
 return {module:module.id,title:module.title,metrics,comparison,findings,assumptions,actions,inputs:module.fields.map(([key,label])=>({label,value:String(v[key])})),currency};
}

export const FIELD_HELP = {
spend:'Include the recurring technology costs you want to assess: hosting, subscriptions, licences or infrastructure. Use one currency throughout.',
reducible:'Exclude fixed commitments you cannot change. Example: if 600,000 of a 1,000,000 monthly bill can be reviewed, enter 60.',
reduction:'This applies only to the changeable portion, not the whole bill. Example: enter 20 to model reducing that portion by one fifth.',
added:'Enter new ongoing costs needed to achieve the target, such as monitoring or support. Enter 0 if none.',
implementation:'Include the one-time project, engineering and migration costs. Enter 0 if none.',
users:'People who actively use this application; this provides context and does not itself create a savings estimate.',
transactions:'Choose one repeatable task, such as submitting an order or generating a report. Count completed tasks in a typical month.',
current:'Measure the same task from start to finish under typical conditions. Example: 12 seconds.',
target:'Enter the target for the same task. Example: 5 seconds. A target is not a measured or guaranteed result.',
dependencies:'Include databases, connected applications, APIs and services. Yes means there is a current written list.',
tests:'Yes means tests exist to confirm that current features still work after software changes.',
servers:'Count the servers or separate application workloads included in this migration.',
data:'Total data to copy, in decimal gigabytes. 1 TB equals 1,000 GB in this estimate.',
bandwidth:'Use the speed available to this transfer, not an advertised maximum. Ask your IT team or hosting provider if unsure.',
efficiency:'Allow for shared traffic and transfer overhead. Enter 60 to model using 60% of the connection. Validate this with a test transfer.',
rto:'The longest interruption your business can tolerate before service must be restored.',
recovery:'Use the duration measured in a recovery exercise, not a promise from a provider. A missing test should be investigated before migration.',
destination:'Check capacity, security, location, compatibility and contractual requirements with the intended provider.',
volume:'The total data currently stored in the system being assessed. 1 TB equals 1,000 GB here.',
growth:'New data kept after deletions in a typical month. Enter 0 if the total is stable.',
archive:'Only include existing data that can safely move to archive storage while meeting retention and access needs. This model keeps it; it does not delete it.',
months:'The estimate projects storage at the end of this period. Example: 12 for one year.',
rate:'Use a storage-only unit rate in the selected currency. Retrieval, transfer and backup charges require separate review.',
archiveRate:'Use the proposed archive tier rate. Include additional retrieval and transfer charges in your later business case.',
inventory:'A current list of computers, servers, applications, databases and cloud services, including who owns them.',
access:'Someone has checked user permissions and removed accounts or privileges that are no longer needed.',
backup:'A recovery exercise has successfully restored usable files or a system from backup. Having a backup alone is not a recovery test.',
monitoring:'Important systems are monitored and alerts reach a named person when a service is unavailable or unhealthy.',
patching:'A named person or team owns software updates, with an agreed schedule and a process for urgent fixes.',
response:'Your team has rehearsed the steps, responsibilities and communication needed during a service outage or security incident.',
release:'Changes require approval and have written instructions for returning to the previous working version if needed.'
};
export function detailedAnalysis(result,module,values){
 const evidence=module.fields.filter(f=>f[2]==='select').map(([key,label])=>({label,status:values[key]==='yes'?'Reported in place':values[key]==='no'?'Needs action':'Needs confirmation',meaning:FIELD_HELP[key],next:values[key]==='yes'?'Collect a dated record or test result to confirm this answer.':values[key]==='no'?'Assign an owner, agree a corrective action and test the result.':'Ask the responsible team for evidence before making a decision.'}));
 const methods={cost:['Monthly reduction = monthly spend × changeable share × reduction target.','Net monthly saving = monthly reduction − new monthly operating costs.','First-year net benefit = 12 × net monthly saving − one-time implementation cost.','Payback = one-time cost ÷ positive net monthly saving.'],modernisation:['Time change = current task time − desired task time.','Monthly processing-time change = time change × monthly task count ÷ 3,600.','Performance change = time change ÷ current task time × 100.','Concurrent tasks may overlap. Processing-time change is not staff time saved.'],migration:['Effective transfer speed = connection speed × usable share.','Bulk copy hours = data in GB × 8,000 ÷ effective Mbps ÷ 3,600.','Recovery gap = the amount the tested recovery time exceeds the business limit.','Setup, repeat copies, validation and cutover add time beyond the bulk copy estimate.'],data:['Future data = current data + monthly growth × number of months.','Archive volume = current data × archive share.','Future active data = future data − archive volume.','Target monthly cost = active GB × active rate + archive GB × archive rate.'],audit:['Each answer is reviewed individually: Yes, No or Unknown.','No identifies a reported gap; Unknown identifies evidence still needed.','Yes requires supporting evidence before the control is considered verified.','No compliance certification or system inspection is performed by this questionnaire.']};
 const gapCount=evidence.filter(e=>e.status==='Needs action').length,unknown=evidence.filter(e=>e.status==='Needs confirmation').length;
 return {summary:module.id==='audit'?`You reported ${gapCount} missing controls and ${unknown} areas that need confirmation. Review each control below and use the action plan to organise a technical assessment.`:`The scenario compares your entered baseline with your target for ${module.title.toLowerCase()}. Review the calculated changes below, then validate the assumptions and prerequisites before approving implementation.`,evidence,methods:methods[module.id],roadmap:[{phase:'1. Confirm the baseline',owner:module.id==='cost'?'Finance and IT owner':'IT or application owner',tasks:['Check the entered figures against current records.',...result.actions.slice(0,1)],deliverable:'An agreed baseline and an evidence list.'},{phase:'2. Design and validate the target',owner:'Technical lead and business sponsor',tasks:[...result.actions.slice(1),'Test a representative change and record acceptance criteria.'],deliverable:'A tested target design, cost estimate and implementation decision.'},{phase:'3. Implement and measure',owner:'Delivery lead and operations owner',tasks:['Agree the change window, responsibilities and recovery plan.','Compare actual outcomes with the baseline and target after implementation.'],deliverable:'Measured outcomes, outstanding issues and operational handover.'}]};
}
