export const MODULES = [
 {id:'cost',title:'Cost optimisation',short:'Cost',description:'Compare current spending with a resource reduction scenario.',fields:[['spend','Current monthly spend','number',0],['reducible','Spend eligible for optimisation (%)','number',0,100],['reduction','Target reduction on eligible spend (%)','number',0,100],['added','Additional monthly operating cost','number',0],['implementation','One-time implementation cost','number',0]],sample:{spend:1000000,reducible:60,reduction:20,added:20000,implementation:300000}},
 {id:'modernisation',title:'Application modernisation',short:'Applications',description:'Compare workflow performance and identify delivery prerequisites.',fields:[['users','Active users','number',1],['transactions','Monthly workflow transactions','number',1],['current','Current transaction time (seconds)','number',0.01],['target','Desired transaction time (seconds)','number',0.01],['dependencies','Documented system dependencies','select',['yes','no','unknown']],['tests','Regression tests available','select',['yes','no','unknown']]],sample:{users:100,transactions:20000,current:12,target:5,dependencies:'yes',tests:'no'}},
 {id:'migration',title:'Cloud migration',short:'Migration',description:'Estimate transfer duration and compare recovery requirements.',fields:[['servers','Servers or workloads','number',1],['data','Data to transfer (GB)','number',0.01],['bandwidth','Available transfer bandwidth (Mbps)','number',0.01],['efficiency','Expected bandwidth efficiency (%)','number',1,100],['rto','Maximum acceptable recovery time (hours)','number',0.01],['recovery','Last tested recovery time (hours)','number',0.01],['dependencies','Dependencies documented','select',['yes','no','unknown']],['destination','Destination requirements confirmed','select',['yes','no','unknown']]],sample:{servers:12,data:2000,bandwidth:200,efficiency:60,rto:4,recovery:8,dependencies:'no',destination:'unknown'}},
 {id:'data',title:'Data optimisation',short:'Data',description:'Model storage growth and a retention or archive scenario.',fields:[['volume','Current stored data (GB)','number',0.01],['growth','Monthly net data growth (GB)','number',0],['archive','Current data eligible for removal/archive (%)','number',0,100],['months','Planning horizon (months)','number',1,120],['rate','Current storage cost per GB / month','number',0],['archiveRate','Archive storage cost per GB / month','number',0],['backup','Backup restoration tested','select',['yes','no','unknown']]],sample:{volume:5000,growth:200,archive:30,months:12,rate:100,archiveRate:20,backup:'yes'}},
 {id:'audit',title:'IT & technical audit',short:'Audit',description:'Review reported controls and prioritise evidence collection.',fields:[['inventory','Current system inventory','select',['yes','no','unknown']],['access','Access review completed','select',['yes','no','unknown']],['backup','Backup restoration tested','select',['yes','no','unknown']],['monitoring','Critical service monitoring in place','select',['yes','no','unknown']],['patching','Patch ownership and process defined','select',['yes','no','unknown']],['response','Incident response procedures tested','select',['yes','no','unknown']],['release','Release approval and rollback documented','select',['yes','no','unknown']]],sample:{inventory:'yes',access:'no',backup:'unknown',monitoring:'yes',patching:'yes',response:'no',release:'unknown'}}
];
export const money=(n,currency='NGN')=>new Intl.NumberFormat('en',{style:'currency',currency,maximumFractionDigits:0}).format(n);
const fmt=n=>new Intl.NumberFormat('en',{maximumFractionDigits:1}).format(n);
export function validate(module,v){const errors={};for(const [key,label,type,min,max] of module.fields){if(type==='select'){if(!min.includes(v[key])) errors[key]='Select a response, including Unknown if needed.';}else if(v[key]===''||v[key]===undefined||!Number.isFinite(Number(v[key]))||Number(v[key])<min||(Number(v[key])>(max??1e12))||(['users','transactions','servers','months'].includes(key)&&!Number.isInteger(Number(v[key]))))errors[key]=`Enter a number from ${min}${max!==undefined?` to ${max}`:' or above'}.`;}return errors;}
export function analyse(module,v,currency='NGN'){
 const n=k=>Number(v[k]);const metrics=[],comparison=[],findings=[],assumptions=[],actions=[];
 const add=(label,value,detail)=>metrics.push({label,value,detail});const row=(label,current,target)=>comparison.push({label,current,target});
 if(module.id==='cost') {const gross=n('spend')*n('reducible')/100*n('reduction')/100,net=gross-n('added'),proposed=n('spend')-net;
 add('Net monthly change',money(net,currency),net>=0?'Projected monthly saving':'Projected additional monthly cost');add('Proposed monthly spend',money(proposed,currency),'After the entered additional operating cost');add('First-year net benefit',money(net*12-n('implementation'),currency),'12 months of net savings less implementation');add('Simple payback',net>0?fmt(n('implementation')/net)+' months':'No positive payback','Implementation cost / positive monthly saving');row('Monthly spend',money(n('spend'),currency),money(proposed,currency));row('Annual recurring spend',money(n('spend')*12,currency),money(proposed*12,currency));
 findings.push({priority:net>0?'Opportunity':'Review',title:net>0?'The entered scenario reduces recurring spend':'The entered scenario does not produce net savings',detail:'Gross monthly reduction is '+money(gross,currency)+'. Additional operating cost is '+money(n('added'),currency)+'.'});assumptions.push('Only the entered eligible portion of spending receives the target reduction.','Constant spending and savings for 12 months. Taxes, exchange-rate movements and financing costs excluded.','Reduction percentages are user targets, not savings identified from invoices.');actions.push('Validate invoices, utilisation and contract commitments.','Confirm engineering effort and implementation costs before approving changes.');
 } else if(module.id==='modernisation'){const change=n('current')-n('target'),hours=change*n('transactions')/3600;add('Target time change',fmt(change)+' sec',change>=0?'Reduction per workflow transaction':'Increase per workflow transaction');add('Aggregate processing change',fmt(hours)+' hours / month','Transaction-time difference multiplied by volume');add('Desired performance change',fmt(change/n('current')*100)+'%','Relative to entered current time');add('Active users',fmt(n('users')),'Reported workload context');row('Transaction time',fmt(n('current'))+' sec',fmt(n('target'))+' sec');
 assumptions.push('Transaction volume stays constant.','Aggregate processing time is not employee time saved or financial benefit.','The desired performance is a target that needs benchmarking.');actions.push('Benchmark the selected workflow and map dependencies.','Agree an architecture approach and test a representative change.');
 } else if(module.id==='migration'){const hours=n('data')*8000/(n('bandwidth')*n('efficiency')/100)/3600;add('Estimated bulk transfer',fmt(hours)+' hours','Decimal GB, entered bandwidth and efficiency');add('Workloads in scope',fmt(n('servers')),'Reported servers or workloads');add('Recovery gap',fmt(Math.max(0,n('recovery')-n('rto')))+' hours','Tested recovery time above the desired maximum');add('Recovery requirement',fmt(n('rto'))+' hours','Client target, not a demonstrated result');row('Recovery time',fmt(n('recovery'))+' hours',fmt(n('rto'))+' hours');
 if(n('recovery')>n('rto'))findings.push({priority:'High',title:'Reported recovery exceeds the requirement',detail:'Recovery design and rehearsal need to close the entered gap.'});assumptions.push('Bulk transfer estimate excludes setup, validation, retries and live data changes.','Transfer time does not equal service downtime or the full migration timeline.','Destination capacity, pricing, residency and contractual terms require separate validation.');actions.push('Inventory workloads and map application dependencies.','Run a representative transfer and rehearse reconciliation, cutover and rollback.');
 } else if(module.id==='data'){const projected=n('volume')+n('growth')*n('months'),archived=n('volume')*n('archive')/100,active=projected-archived,baseline=projected*n('rate'),target=active*n('rate')+archived*n('archiveRate');add('Projected data volume',fmt(projected)+' GB','At the end of the planning horizon');add('Target active storage',fmt(active)+' GB','Archive only the eligible portion of current data');add('Archive volume',fmt(archived)+' GB','Data remains stored in the archive scenario');add('Monthly storage difference',money(baseline-target,currency),'End-of-horizon estimate, not cumulative savings');row('Active storage',fmt(projected)+' GB',fmt(active)+' GB');row('Monthly storage cost',money(baseline,currency),money(target,currency));assumptions.push('Linear net growth. New data remains in active storage.','Archive eligibility is a user assumption subject to retention and access requirements.','Costs exclude transfer, retrieval, requests, backups and implementation.');actions.push('Confirm retention requirements and identify suitable datasets.','Measure query performance and test restoration before changing storage tiers.');
 } else {const responses=module.fields.map(([k,l])=>({label:l,value:v[k]})),yes=responses.filter(x=>x.value==='yes').length,no=responses.filter(x=>x.value==='no').length,unknown=responses.length-yes-no;add('Reported controls in place',`${yes} / ${responses.length}`,'Self-reported coverage, not a compliance score');add('Reported gaps',String(no),'Responses marked No');add('Evidence to confirm',String(unknown),'Responses marked Unknown');add('Assessment basis','Self-reported','No system inspection has taken place');responses.forEach(x=>row(x.label,x.value==='yes'?'Reported in place':x.value==='no'?'Reported missing':'Unknown','Evidence confirmed'));assumptions.push('Each response reflects the user’s knowledge at the time of assessment.','Reported controls need documentary or system evidence. This is not certification or a completed technical audit.');actions.push('Collect evidence for reported controls and unknown responses.','Agree a technical assessment scope with owners for critical systems.');}
 for(const [key,label,type] of module.fields)if(type==='select'&&v[key]!=='yes')findings.push({priority:v[key]==='no'?'High':'Verify',title:label,detail:v[key]==='no'?'Reported missing. Agree an owner and remediation plan.':'Unknown. Collect evidence before drawing a technical conclusion.'});
 if(!findings.length)findings.push({priority:'Verify',title:'Validate the scenario with system evidence',detail:'Confirm entered parameters and test the target state before implementation.'});
 return {module:module.id,title:module.title,metrics,comparison,findings,assumptions,actions,inputs:module.fields.map(([key,label])=>({label,value:String(v[key])})),currency};
}
